[supabase]
#db_url = "postgresql://postgres:%408minWvVyCR_JUF@db.gxtfoogyyqcsgtjymelw.supabase.co:5432/postgres"
db_url = "postgresql://postgres.gxtfoogyyqcsgtjymelw:%408minWvVyCR_JUF@aws-1-eu-west-1.pooler.supabase.com:6543/postgres"

[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
smtp_user = "frodeoffline@gmail.com"
smtp_password = "mmbkqllorltyxwgc"
admin_epost = "frodeoffline@gmail.com"

[passwords]
admin = "admin123"
lagleder = "dommer123"
dommer = "fløyte"